### ISSUE TITLE
[no-var-requires] rule also checks js files

### ISSUE THREAD

**Issue by rodrigojcmello** [typescript-eslint/typescript-eslint#1291]
I believe this rule is unique to typescript files, but it is being checked in a javascript file.

.eslint.yml:

```YML
env:
  browser: true
  es6: true
  node: true

parser: '@typescript-eslint/parser'

extends:
  - 'plugin:react/recommended'
  - airbnb
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - react
  - '@typescript-eslint'
  - prettier

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  max-lines: 1
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.tsx'

settings:
  react:
    version: detect
    import/resolver:
      node:
        extensions:
          - '.ts'
          - '.tsx'
```

No ts file, this rule checks a js file
```JS
const withSass = require('@zeit/next-sass'); // no-var-requires HERE

module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    localIdentName: '[hash:base64:5]'
  }
});
```

tsconfig:
```JSON
{
  "compilerOptions": {
    "jsx": "preserve",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "isolatedModules": true
  },
  "exclude": [
    "next.config.js",
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.9.1-alpha.12` |
| `@typescript-eslint/parser`        | `2.9.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.7.2` |
| `node`                             | `13.1.0` |
| `npm`                              | `3.13.1` |
