### ISSUE TITLE
[no-unused-var] False positive when declaring interface in namespace with the same name

### ISSUE THREAD

**Issue by Guillaume-Mayer** [typescript-eslint/typescript-eslint#2595]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
*index.d.ts*
```ts
declare namespace A {
  export interface A {
    foo: string;
  }
}
```

**Expected Result**

No warning or a warning if the namespace is never used.

**Actual Result**

Give me this warning: **'A' is defined but never used.**, on the namespace (even if it's used).

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `4.0.3` |
| `ESLint`                           | `7.9.0` |
| `node`                             | `12.18.4` |

**Config**

```yaml
parser: "@typescript-eslint/parser"

extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
- prettier/@typescript-eslint
- plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  project: ./tsconfig.json

rules:
  "@typescript-eslint/no-floating-promises": error

ignorePatterns:
- dist/
```
