### ISSUE TITLE
New rule: no-useless-empty-export

### ISSUE THREAD

**Issue by remcohaszing** [typescript-eslint/typescript-eslint#2757]
In TypeScript, modules are TypeScript files that contain an import or export statement. If a file is not a module, it will be ignored by TypeScript. Sometimes a file doesn’t contain imports or exports for legitimate reasons. In this case, an empty export must be added. I.e. to augment an interface:

```ts
export {};

declare module '@appsemble/sdk' {
  interface Parameters {
    interval: number;
  }

  interface EventEmitters {
    interval: never;
  }
}
```

As soon as the file is modified to contain actual imports or exports, the empty export can be removed.

I’d like to propose a rule that reports empty exports if the file contains other imports / exports. This can be autofixable by removing the empty export. I’m willing to implement this.

**Comment by remcohaszing** [comment]
Perhaps even an option could be added to make an export required if no imports are present. Maybe this would be even better.

```yaml
rules:
  @typescript-eslint/valid-module:
    - error
      # Removes an empty export if there are other imports or exports. Autofix removes the empty export.
    - allowUselessExport: false
      # Requires an empty export if there are no other imports or exports. Autofix adds an empty export to the end of the file.
      requireModuleSyntax: true
```
