### ISSUE TITLE
[member-ordering] ordering of fields that contain references to other fields

### ISSUE THREAD

**Issue by ljwagerfield** [typescript-eslint/typescript-eslint#2882]
**Repro**

```yaml
"@typescript-eslint/member-ordering":
    - error
    - default:
        order: alphabetically
        memberTypes:
          - "signature"
          - "field"
          - "constructor"
          - "method"
```

```TS
readonly a: number = this.b + this.c // Forward reference (error)
readonly b: number = 42
readonly c: number = 100
```

**Expected Result**

Linting rules would make an exception for `a` to be placed after `b` and `c` (as it needs to be that way to compile).

OR

I am able to configure the rules such that fields have a more relaxed set of rules (i.e. `order: 'as-written'`) while everything else, like methods, have stricter rules (i.e. `order: 'alphabetically'`).

**Actual Result**

ESlint forces me to arrange the code in a way that it fails at runtime, due to `this.b` and `this.c` not being initialised at the point they're referenced in `this.a`.

**Additional Info**

I current work around this by setting `// eslint-disable-line` on my `readonly` statements... but it's getting a little ugly.

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.8.1` |
| `@typescript-eslint/parser`               | `4.8.1` |
| `TypeScript`                              | `4.1.2` |
| `ESLint`                                  | `7.13.0` |
| `node`                                    | `12` |
