### ISSUE TITLE
[no-inferrable-types] conflict in function params of any with default value

### ISSUE THREAD

**Issue by Mister-Hope** [typescript-eslint/typescript-eslint#3145]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```yaml
root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

overrides:

  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - ./tsconfig.json
        - ./tests/e2e/tsconfig.json

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - warn

```

```TS
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Mutation = (id: string, payload?: any) => void;

export const mutation: Mutation = (id, isLogin: boolean = true) => {
  id = isLogin.toString();
};

```

TsConfig:

```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "baseUrl": ".",
    "declaration": true,
    "diagnostics": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "inlineSourceMap": false,
    "inlineSources": false,
    "jsx": "preserve",
    "listEmittedFiles": true,
    "module": "esnext",
    "moduleResolution": "node",
    "noEmitHelpers": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "resolveJsonModule": true,
    "removeComments": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "esnext",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/unit/**/*.ts",
    "typings/**/*.ts"
  ]
}
```

test/e2e/tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  },
  "include": ["**/*.ts"]
}
```

![image](https://user-images.githubusercontent.com/33315834/109962417-1df8b580-7d26-11eb-8da5-0068d8a99493.png)
![image](https://user-images.githubusercontent.com/33315834/109962457-2b15a480-7d26-11eb-8fdf-4f92f03a5ca0.png)

I am expecting `@typescript-eslint/no-inferrable-types` not throwing any errors.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.16.1` |
| `@typescript-eslint/parser`        | `4.16.1` |
| `TypeScript`                       | `4.2.2` |
| `ESLint`                           | `7.21.0` |
| `node`                             | `14.15.5` |
