### ISSUE TITLE
Using native eslint rules config in .eslintrc

### ISSUE THREAD

**Issue by avalanche1** [typescript-eslint/typescript-eslint#823]
`typescript-eslint` is reporting errors on rules I have disabled in `.eslintrc`. 
How can I use basic eslint rules instead of typing `rules: {  @typescript-eslint/camelcase: "off" }`?

**What code were you trying to parse?**

`Code:`
```ts
function get_json(){
  ///some code
}
```

`.eslintrc.yml:`
```yaml
env:
  node: true
  browser: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "hardcore-fp"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "plugin:promise/recommended"
  - prettier
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2017,
  sourceType: module
plugins:
  - "@typescript-eslint/eslint-plugin"
  - jest
  - react
  - react-hooks
  - promise
overrides:
  - files:
      - "*.test.js"
      - "*.spec.js"
    rules:
      fp/no-unused-expression: "off"
rules:
  arrow-body-style: "off"
  camelcase: "off"
```

**What did you expect to happen?**
No errors reported.
**What actually happened?**
` error    Identifier 'get_json' is not in camel case           @typescript-eslint/camelcase`
**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `^1.13.0` |
| `TypeScript`                | `^3.5.3` |
| `ESLint`                    | `^5.16.0` |
