### ISSUE TITLE
[explicit-function-return-type] Freaks out at .js files

### ISSUE THREAD

**Issue by lolmaus** [typescript-eslint/typescript-eslint#964]
**Repro**

<details><summary>Affected file: config/dotenv.js (JS!!!)</summary><p>

```js
const fs = require("fs");

const DEFAULT_DOTENV_NAME = "dev-mirage";

module.exports = function(env) {
  const dotenvName =
    env === "test"
      ? "test"
      : process.env.DOTENV && process.env.DOTENV.length > 0
      ? process.env.DOTENV
      : DEFAULT_DOTENV_NAME;

  const dotenvFileName = `.env-${dotenvName}`;

  if (fs.existsSync(dotenvFileName)) {
    console.info(`Using dotenv file: ${dotenvFileName}`);
  } else {
    console.warn(
      `dot-env file not found: ${dotenvFileName}, assuming env vars are passed manually`,
    );
  }

  return {
    clientAllowedKeys: [],
    // Fail build when there is missing any of clientAllowedKeys environment variables.
    // By default false.
    failOnMissingKey: false,
    path: dotenvFileName,
  };
};

```

</p></details>

<details><summary>.eslintrc.yml</summary><p>

```yml
---
root: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

  # Required for `plugin:@typescript-eslint/recommended-requiring-type-checking`
  # which needs both browser and Node environments configured explicitly
  project:
  - "./tsconfig.json"
  - "./tsconfig-node.json"

plugins:
  - "@typescript-eslint"
  - ember
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:ember/recommended
  - standard

  - prettier/@typescript-eslint
  - prettier/standard

  # This one should come last
  - plugin:prettier/recommended

env:
  browser: true

rules:
  "@typescript-eslint/ban-ts-ignore":                 off # Can't fully get rid of it due to TS quirks and issues with third-party depenecies
  "@typescript-eslint/camelcase":                     off # Allow two levels of separation, e. g. ProductWizard_SidebarConfig_ListWithHeader_Component_Args
  "@typescript-eslint/class-name-casing":             off # Allow two levels of separation, e. g. ProductWizard_SidebarConfig_ListWithHeader_Component_Args
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/no-empty-interface":            off
  "@typescript-eslint/no-explicit-any":               off
  "@typescript-eslint/no-unused-vars":                [error, {argsIgnorePattern: "^_"}]
  "@typescript-eslint/no-useless-constructor":        error
  "@typescript-eslint/unbound-method":                off

  camelcase:              off
  new-cap:                off
  no-console:             [error, {allow: [warn, error, info, debug]}]
  no-useless-constructor: off
  prefer-const:           error
  prettier/prettier:      [error, {arrowParens: always, trailingComma: all}]



overrides:
  -
    files:
      - .ember-cli.js
      - .eslintrc.js
      - .template-lintrc.js
      - ember-cli-build.js
      - testem.js
      - blueprints/*/index.js
      - config/**/*.js
      - lib/*/index.js
      - server/**/*.js
    excludedFiles:
      - app/**
    parserOptions:
      sourceType: script
      ecmaVersion: 2015
    env:
      browser: false
      node: true
    plugins:
      - node
    rules:
      "@typescript-eslint/no-var-requires": off
      no-process-exit: error
      node/no-deprecated-api: error
      node/no-extraneous-require: error
      node/no-missing-require: error
      node/no-unpublished-bin: error
      node/no-unpublished-require: off
      node/no-unsupported-features/es-builtins: error
      node/no-unsupported-features/es-syntax: [error, {ignores: []}]
      node/no-unsupported-features/node-builtins: error
      node/process-exit-as-throw: error
      node/shebang: error
      node/no-extraneous-import: off
      node/no-missing-import: off
      node/no-unpublished-import: off
    extends:
      - plugin:node/recommended

  -
    files:
      - tests/**/*-test.ts
      - tests/**/*-test.js

    rules:
      no-unused-expressions: off
```

</p></details>

<details><summary>tsconfig-node.json</summary><p>

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "es6",
    "moduleResolution": "node",
    "noEmit": true,
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "es2017",
    "skipLibCheck": true
  },
  "include": [
    ".ember-cli.js",
    ".eslintrc.js",
    ".template-lintrc.js",
    "ember-cli-build.js",
    "testem.js",
    "blueprints/*/index.js",
    "config/**/*.js",
    "lib/*/index.js",
    "server/**/*.js"
  ]
}
```

</p></details>

**Expected Result**

No TS-specific linting errors reported for a JS file.

**Actual Result**

```
C:\Code\kaliber5\wbc\config\dotenv.js
  5:18  error  Missing return type on function  @typescript-eslint/explicit-function-return-type
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.2.0` |
| `@typescript-eslint/parser`        | `2.2.0` |
| `TypeScript`                       | `3.6.2` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.9.0` |
| `npm`                              | `1.17.3` |
